# Generated by Django 6.0.3 on 2026-04-03 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Productos'},
        ),
    ]
