# Generated by Django 6.0.3 on 2026-04-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=300)),
                ('status', models.CharField(choices=[('P', 'pending'), ('I', 'in progress'), ('C', 'completed')], max_length=1)),
                ('priority', models.CharField(choices=[('L', 'low'), ('R', 'regular'), ('H', 'high')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
